"""make_cuts: cut raw video files at cut positions generated by generate_cuts"""

import os
import files
import sys

def make_cut(output_path: str, movie_path: str, start: float, end: float):
    """Cut the movie located at <movie_path>, beginning at <start> seconds and ending
    at <end> seconds, saving it to the file <output_path>"""
    # stream = ffmpeg.input(movie_path)
    # stream = ffmpeg.trim(stream, start=start, end=end)
    # stream = ffmpeg.output(stream, output_path)
    # ffmpeg.run(stream)
    os.system(f'ffmpeg -i "{movie_path}" -ss {start} -to {end} "{output_path}"')


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <data directory>")
        exit(1)
    directory = sys.argv[1]
    movies = files.get_movies(directory)
    cuts = files.read_cuts(directory)
    if not os.path.exists(os.path.join(directory, 'output')):
        print("Creating output directory...")
        os.mkdir(os.path.join(directory, 'output'))
    try:
        for cut in cuts:
            print(f"Starting cut for clip ID {cut['clip_id']}")
            output_path = os.path.join(directory, 'output', f"{cut['clip_id']}.mp4")
            movie_path = os.path.join(directory, movies[cut['movie_id']])
            start = float(cut['start_sec'])
            end = float(cut['end_sec'])
            make_cut(output_path, movie_path, start, end)
    except BaseException as exception:
        print(f"Uncaught exception: {repr(exception)}")
        print("Aborting...")
    finally:
        print("Done making cuts, terminate make_cuts")